### ISSUE TITLE
minor: typo in repo's "About"

### ISSUE THREAD

**Issue by herczogzoltan** [go-furnace/go-furnace#69]
Currently the "About" of the repo has a minor typo:

Go Hosting Solution for AWS, Google "Could" and Digital Ocean 

Thanks for your work btw!:)

**Comment by Skarlso** [comment]
@herczogzoltan Yoooooo :DDD

This old thing, hah. :)))))))

**Comment by Skarlso** [comment]
Fixed :)

**Comment by herczogzoltan** [comment]
Yo!:D Thanks a lot!:D 🙌

**Comment by Skarlso** [comment]
The pleasure was all mine.:D
